// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZIyROvHE_xMCVo6DhTZUznJPvRXizG-0',
    appId: '1:872238658916:web:564a8cfbf085ce11bdb671',
    messagingSenderId: '872238658916',
    projectId: 'ecommerce-app-1b40f',
    authDomain: 'ecommerce-app-1b40f.firebaseapp.com',
    storageBucket: 'ecommerce-app-1b40f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMvm_7pkzoBTiA4HweP0gmuR7AteZXdRk',
    appId: '1:872238658916:android:e72b76b0599c7891bdb671',
    messagingSenderId: '872238658916',
    projectId: 'ecommerce-app-1b40f',
    storageBucket: 'ecommerce-app-1b40f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk6UpSRI5HudUk3Qw8mxg-e6ynNt3OC4Y',
    appId: '1:872238658916:ios:20c3e60926be4025bdb671',
    messagingSenderId: '872238658916',
    projectId: 'ecommerce-app-1b40f',
    storageBucket: 'ecommerce-app-1b40f.appspot.com',
    androidClientId: '872238658916-hmq795ejljumceirk1l9i7fc8b37n683.apps.googleusercontent.com',
    iosClientId: '872238658916-qlpvoakdmeaq8ru0j7dgi73oh9aev9hm.apps.googleusercontent.com',
    iosBundleId: 'com.ecommerapp.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZIyROvHE_xMCVo6DhTZUznJPvRXizG-0',
    appId: '1:872238658916:web:f835e561d2be8ac6bdb671',
    messagingSenderId: '872238658916',
    projectId: 'ecommerce-app-1b40f',
    authDomain: 'ecommerce-app-1b40f.firebaseapp.com',
    storageBucket: 'ecommerce-app-1b40f.appspot.com',
  );

}